// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class AS4Test
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void insuranceQuote1()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(1058, 816);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Darshil");
        driver.FindElement(By.Id("lastName")).SendKeys("Anghan");
        driver.FindElement(By.Id("address")).SendKeys("King Street");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2N 0K3");
        driver.FindElement(By.Id("phone")).SendKeys("123-123-1234");
        driver.FindElement(By.Id("email")).SendKeys("da@gmail.com");
        driver.FindElement(By.Id("age")).SendKeys("24");
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$4500"));
        }
    }
    [Test]
    public void insuranceQuote2()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(1062, 816);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Darshil");
        driver.FindElement(By.Id("lastName")).SendKeys("Anghan");
        driver.FindElement(By.Id("address")).SendKeys("king Street");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).Click();
        driver.FindElement(By.Id("postalCode")).SendKeys("N2N 0K0");
        driver.FindElement(By.Id("phone")).SendKeys("123-345-5678");
        driver.FindElement(By.Id("email")).SendKeys("da@gmail.com");
        driver.FindElement(By.Id("age")).SendKeys("25");
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).SendKeys("4");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("No Insurance for you!!  Too many accidents - go take a course!"));
        }
    }
    [Test]
    public void insuranceQuote3()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(1062, 816);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Darshil");
        driver.FindElement(By.Id("lastName")).Click();
        driver.FindElement(By.Id("lastName")).SendKeys("Anghan");
        driver.FindElement(By.Id("address")).Click();
        driver.FindElement(By.Id("address")).SendKeys("King Street");
        driver.FindElement(By.Id("city")).Click();
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).Click();
        driver.FindElement(By.Id("postalCode")).SendKeys("N2N 0K3");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("123-345-5678");
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys("da@gmail.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("35");
        driver.FindElement(By.Id("experience")).SendKeys("9");
        driver.FindElement(By.Id("accidents")).SendKeys("2");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$3285"));
        }
    }
    [Test]
    public void insuranceQuote4()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(1066, 816);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Darshil");
        driver.FindElement(By.Id("lastName")).SendKeys("Anghan");
        driver.FindElement(By.Id("address")).SendKeys("King Street");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2N 0K3");
        driver.FindElement(By.Id("phone")).SendKeys("1233455678");
        driver.FindElement(By.Id("email")).SendKeys("da@gmail.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("27");
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("phone-error")).Text, Is.EqualTo("Phone Number must follow the patterns 111-111-1111 or (111)111-1111"));
    }
    [Test]
    public void insuranceQuote5()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(1070, 816);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Darshil");
        driver.FindElement(By.Id("lastName")).SendKeys("Anghan");
        driver.FindElement(By.Id("address")).SendKeys("King Street");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2N 0K3");
        driver.FindElement(By.Id("phone")).SendKeys("1233455678");
        driver.FindElement(By.Id("email")).SendKeys("da@gmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("123-345-5678");
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys("da");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("28");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("email-error")).Text, Is.EqualTo("Must be a valid email address"));
    }
    [Test]
    public void insuranceQuote6()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(1076, 816);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Darshil");
        driver.FindElement(By.Id("lastName")).SendKeys("Anghan");
        driver.FindElement(By.Id("address")).SendKeys("King Street");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2N 0K3");
        driver.FindElement(By.Id("phone")).SendKeys("1233455678");
        driver.FindElement(By.Id("email")).SendKeys("da@gmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("123-345-5678");
        driver.FindElement(By.Id("postalCode")).Click();
        driver.FindElement(By.Id("postalCode")).SendKeys("N2N 0K");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("35");
        driver.FindElement(By.Id("experience")).SendKeys("15");
        driver.FindElement(By.Id("accidents")).SendKeys("1");
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("postalCode-error")).Text, Is.EqualTo("Postal Code must follow the pattern A1A 1A1"));
    }
    [Test]
    public void insuranceQuote7()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(1078, 816);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Darshil");
        driver.FindElement(By.Id("lastName")).SendKeys("Anghan");
        driver.FindElement(By.Id("address")).SendKeys("King Street");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2N 0K3");
        driver.FindElement(By.Id("phone")).SendKeys("1233455678");
        driver.FindElement(By.Id("email")).SendKeys("da@gmail.com");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("5");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("123-345-5678");
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("age-error")).Text, Is.EqualTo("Age (>=16) is required"));
    }
    [Test]
    public void insuranceQuote9()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(1086, 816);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Darshil");
        driver.FindElement(By.Id("lastName")).SendKeys("Anghan");
        driver.FindElement(By.Id("address")).SendKeys("King Street");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2N 0K3");
        driver.FindElement(By.Id("phone")).SendKeys("1233455678");
        driver.FindElement(By.Id("email")).SendKeys("da@gmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("123-345-5678");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("45");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("experience-error")).Text, Is.EqualTo("Years of experience is required"));
    }
    [Test]
    public void insuranceQuote10()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(1058, 816);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Darshil");
        driver.FindElement(By.Id("lastName")).SendKeys("Anghan");
        driver.FindElement(By.Id("address")).SendKeys("King Street");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2N 0K3");
        driver.FindElement(By.Id("phone")).SendKeys("1233455678");
        driver.FindElement(By.Id("email")).SendKeys("da@gmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("123-345-5678");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("24");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("5");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$4500"));
        }
    }
    [Test]
    public void insuranceQuote11()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(1062, 816);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Darshil");
        driver.FindElement(By.Id("lastName")).SendKeys("Anghan");
        driver.FindElement(By.Id("address")).SendKeys("King Street");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2N 0K3");
        driver.FindElement(By.Id("phone")).SendKeys("1233455678");
        driver.FindElement(By.Id("email")).SendKeys("da@gmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("123-345-5678");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("35");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("12");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$2190"));
        }
    }
    [Test]
    public void insuranceQuote12()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(1066, 816);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Darshil");
        driver.FindElement(By.Id("lastName")).SendKeys("Anghan");
        driver.FindElement(By.Id("address")).SendKeys("King Street");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2N 0K3");
        driver.FindElement(By.Id("phone")).SendKeys("1233455678");
        driver.FindElement(By.Id("email")).SendKeys("da@gmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("123-345-5678");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("29");
        driver.FindElement(By.Id("experience")).SendKeys("8");
        driver.FindElement(By.Id("accidents")).SendKeys("2");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$4500"));
        }
    }

    [Test]
    public void insuranceQuote13()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(1070, 816);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Darshil");
        driver.FindElement(By.Id("lastName")).SendKeys("Anghan");
        driver.FindElement(By.Id("address")).SendKeys("King Street");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2N 0K3");
        driver.FindElement(By.Id("phone")).SendKeys("1233455678");
        driver.FindElement(By.Id("email")).SendKeys("da@gmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("123-345-5678");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("30");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("13");
        driver.FindElement(By.Id("accidents")).SendKeys("2");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$2190"));
        }
    }
    [Test]
    public void insuranceQuote14()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(1074, 816);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Darshil");
        driver.FindElement(By.Id("lastName")).SendKeys("Anghan");
        driver.FindElement(By.Id("address")).SendKeys("King Street");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2N 0K3");
        driver.FindElement(By.Id("phone")).SendKeys("1233455678");
        driver.FindElement(By.Id("email")).SendKeys("da@gmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("123-345-5678");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("40");
        driver.FindElement(By.Id("experience")).SendKeys("15");
        driver.FindElement(By.Id("accidents")).SendKeys("2");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$2190"));
        }
    }
    [Test]
    public void insuranceQuote15()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(1078, 816);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Darshil");
        driver.FindElement(By.Id("lastName")).SendKeys("Anghan");
        driver.FindElement(By.Id("address")).SendKeys("King Street");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2N 0K3");
        driver.FindElement(By.Id("phone")).SendKeys("1233455678");
        driver.FindElement(By.Id("email")).SendKeys("da@gmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("123-345-5678");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("40");
        driver.FindElement(By.Id("experience")).SendKeys("16");
        driver.FindElement(By.Id("accidents")).SendKeys("5");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("No Insurance for you!!  Too many accidents - go take a course!"));
        }
    }
    [Test]
    public void insuranceQuote8()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(1066, 816);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Darshil");
        driver.FindElement(By.Id("lastName")).SendKeys("Anghan");
        driver.FindElement(By.Id("address")).SendKeys("King Street");
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2N 0K3");
        driver.FindElement(By.Id("phone")).SendKeys("1233455678");
        driver.FindElement(By.Id("email")).SendKeys("da@gmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("123-345-5678");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("37");
        driver.FindElement(By.Id("experience")).SendKeys("8");
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("accidents-error")).Text, Is.EqualTo("Number of accidents is required"));
    }
}
